### ISSUE TITLE
Use defaults instead of vars in roles for default parameters

### ISSUE THREAD

**Issue by rricard** [osxc/legacy-common#12]

**Comment by arubdesu** [comment]
For reference, I banged my head against this for a bit until it clicked, applicable doc: http://docs.ansible.com/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable
Salient part: `if you are writing a redistributable role with reasonable defaults, put those in the 'roles/x/defaults/main.yml' file. This means the role will bring along a default value but ANYTHING in Ansible will override it`
