### ISSUE TITLE
Explanation of roles

### ISSUE THREAD

**Issue by rizkysyazuli** [osxc/legacy-common#2]
i'm still on the edge with osxc. seems very useful for setting up a new mac. but i need explanations of [the available roles](https://www.dropbox.com/s/y3w7yjxa09z5qde/Screenshot%202014-05-05%2014.42.29.png), what they do, and how to use it in my `all.yml` file.

![screenshot 2014-05-05 14 42 29](https://cloud.githubusercontent.com/assets/152221/2875954/89f1c3dc-d42a-11e3-97a5-55c5ebd267c4.png)

most of it are quite obvious. but roles like `dock`, `maximum_awesome` or `oh_my_zsh` is mysterious to me. could you possibly put this in a wiki or something?

btw, will there be roles to change OS settings?

thx!

**Comment by rricard** [comment]
Yeah ! Documentation is still at it's most early stage ! I will describe them as soon as possible ! To answer quickly:
- brew/cask/gem/git/npm/pip_package installs a package from a special source
- dashboard can disable your annoying os x dashboard (parameter disabled: YES)
- dock can manage your dock icons (see [this](https://github.com/rricard/xc-custom/blob/master/all.yml) for an example)
- homebrew/_cask installs homebrew + cask
- maximum_awesome this is a fantastic tmuxconfig/vimrc [repo](https://github.com/square/maximum-awesome) by square
- oh_my_zsh is an awesome [dotfile for zsh](https://github.com/robbyrussell/oh-my-zsh/)
- rbenv installs rubies 

Again, more doc is coming ASAP !

**Comment by rizkysyazuli** [comment]
cool! thx for the quick response. will try it out.
