### ISSUE TITLE
rbenv installs latest ruby, but gem_package installs to system ruby

### ISSUE THREAD

**Issue by rjacoby** [osxc/legacy-common#23]
Maybe I'm missing something in my ansible playbook setup, but what I'm seeing is the following behavior:
1. rbenv role runs, installs ruby 2.1.1
2. gem_package roles run, but rbenv hasn't been evaluated by ansible so the ruby of current install scope is not the new 2.1.1, but the OSX standard /usr/bin/ruby
3. gems are installed, but in OSX system ruby, **not** in the rbenv'd 2.1.1
4. Then I need to manually re-install the gems in a shell that's been launched with rbenv evaluated.

Playbook as follows:

```

---
- hosts: all
  - role: rbenv
  - role: gem_package
    package_name: bundler
```

**Comment by rricard** [comment]
That's true, we need to link the rbenv shim before installing the gem.

**Comment by smt** [comment]
:+1: I got bit by this issue tonight. There was that funny "where are my gems" moment that we all know and love ;)
