### ISSUE TITLE
homebrew task clones repo even if homebrew is already installed.

### ISSUE THREAD

**Issue by hartzell** [osxc/legacy-common#30]
If I understand the homebrew/tasks/main.yml file correctly, it clones the homebrew repo into `{{brew_repo_path}}` and then very carefully does nothing with it if homebrew is already installed (in particular, if /usr/local/bin/brew exists).

Why even clone it at all in that case?

In other words, should 'clone homebrew' come after 'assert new homebrew installation'?

**Comment by rricard** [comment]
In fact, the name of the task is mistaking. It should be more : ensure that homebrew is cloned AND at the latest version on master. So yeah, we need to run it every time to ensure that homebrew is up to date

**Comment by hartzell** [comment]
I'm still confused.  Thanks for helping me figure out how all of this is stitched together.

Take my system as an example.  I installed homebrew via their instructions before I ever heard of osxc, so my /usr/local/ is a clone of the homebrew repo.

```
$ git remote show origin
* remote origin
  Fetch URL: https://github.com/Homebrew/homebrew.git
  Push  URL: https://github.com/Homebrew/homebrew.git
  HEAD branch: master
  Remote branches:
    gh-pages tracked
    go       tracked
    master   tracked
  Local ref configured for 'git push':
    master pushes to master (local out of date)
```

If/when I run the playbook, it will 
1. clone the repo into {{ brew_repo_path }}
2. check to see if /usr/local/bin/brew exists
3. if /usr/local/bin/brew does not exist, copy /usr/local to {{  brew_repo_path }}
4. if /usr/local/bin/brew does not exist, fix user acls
5. if /usr/local/bin/brew does not exist, clean up acls
6. if /usr/local/bin/brew does not exist, clean up /usr/local
7. if /usr/local/bin/brew does not exist, link the repo...
8. update homebrew

Given that /usr/local/bin/brew already exists, steps 2-7 will not run on my system.  Since the homebrew module just runs the "brew update" command, it should update my existing brew installation successfully.

But, there's still that copy osxc cloned that isn't being used for anything.

Additionally, the copy step seems scary.  Since the src path has a trailing /, the contents of the directory are copied recursive into the directory that contains the fresh copy of the homebrew git repo.
