### ISSUE TITLE
{{ brew_repo_path }} might rather be ~/src/github.com/Homebrew/homebrew

### ISSUE THREAD

**Issue by hartzell** [osxc/legacy-common#32]
It looks like the homebrew stuff now lives under an org account named Homebrew, rather than under mxcl's account.

In the spirit of consistently cloning into dirs in ~/src/github.com named after the account, in xc-common/roles/homebrew/defaults/main.yml, should 

> brew_repo_path: "{{ ansible_env.HOME }}/src/github.com/mxcl/homebrew"

instead be

> brew_repo_path: "{{ ansible_env.HOME }}/src/github.com/Homebrew/homebrew"

**Comment by hacfi** [comment]
:+1: 

off-topic question: How can I use brew install options like `--with-xxx`? Is that already supported?

**Comment by ninjabong** [comment]
yeah looks like for [ansible's homebrew module](http://docs.ansible.com/homebrew_module.html) you just need to use something like this:
homebrew: name=foo install_options=with-xxx

edit:
my bad - I just took a closer and osxc is actually wrapping ansible's homebrew in roles/brew_package, looks like a simple fix would be to add an optional variable for any --with options to pass, and use that as a conditional.

I'll whip up a PR for it tomorrow.

**Comment by ninjabong** [comment]
Here's the [PR](https://github.com/osxc/xc-common/pull/35).
