### ISSUE TITLE
Local configuration Hello World?

### ISSUE THREAD

**Issue by pe3** [osxc/legacy-common#34]
Hi.
How should one start learning to write new roles (I have golang in my mind)? Ansible documentation and tutorials are geared towards managing servers. What do you need to think differently in osxc-style?

What would the code to check if a file exists and load it from GitHub if it is missing look like?

**Comment by ninjabong** [comment]
To check for a file's existence you wanna use ansible's [stat](http://docs.ansible.com/stat_module.html) along with it's [register variable](http://docs.ansible.com/playbooks_variables.html) and [when conditional](http://docs.ansible.com/playbooks_conditionals.html), and you'd have something like this in your roles/foo/tasks/main.yml:

\- name: Check for file
&nbsp;&nbsp;stat: path=/path/to/foo
&nbsp;&nbsp;register: foo_found

\- name: Git clone when absent
&nbsp;&nbsp;git: "repo=https://github.com/foo/bar.git dest=~/src/github.com/foo/bar"
&nbsp;&nbsp;when: foo_found.stat.exists == false

edit: fixed typo, linked variables in ansible docs

**Comment by pe3** [comment]
@ninjabong thaks - that helped me get going. it also helped when i found `ansible <host_pattern> -m <module_name> -a <module_args> <additional_args>` and started playing with it. tried things like `ansible all -m command -a "uptime"`.

**Comment by ninjabong** [comment]
Glad you got going with it!

And that's a neat trick I didn't know about!  Way quicker than editing a test playbook manually everytime.  While I'm working on something I've just been using alot of ansible-playbook playbook.yml -vvv -C until things start needing to be actually run, saves on things like constantly recloning git repos.
