### ISSUE TITLE
Variable substitution priority in all.yml

### ISSUE THREAD

**Issue by octplane** [osxc/legacy-common#5]
Something's weird.
Whatever I do, my git name is configured to Bob example, although my xc-custom contains the correct value (the email parameter is not ignored and the name is):

```
TASK: [git | configure name] ************************************************** 
changed: [localhost] => {"changed": true, "cmd": ["git", "config", "--global", "user.name", "Bob Example"], "delta": "0:00:00.008788", "end": "2014-05-05 14:47:38.739198", "item": "", "rc": 0, "start": "2014-05-05 14:47:38.730410", "stderr": "", "stdout": ""}
```

I have the same issue with rbenv rubies), it always install 2.1.1 regardless of my all.yml configuration:

```
TASK: [rbenv | install and build rubies] ************************************** 
skipping: [localhost] => (item=2.1.1)

TASK: [rbenv | set 2.0.0-p195 as global ruby] ********************************* 
changed: [localhost] => {"changed": true, "cmd": ["rbenv", "global", "2.1.1"], "delta": "0:00:00.043683", "end": "2014-05-05 14:57:55.417448", "item": "", "rc": 0, "start": "2014-05-05 14:57:55.373765", "stderr": "", "stdout": ""}
```

Note the curious discrepancy between the item=2.1.1 and the set 2.0.0-p195 as global ruby (here the rubies parameter is ignored and the global is not).

cf https://github.com/octplane/xc-custom/blob/master/all.yml#L31 (I'm using another ansible syntax, but the one in the default all.yml has the same effects).

This makes me sad, as I can only commit as Bob Example and my coworker make fun of me :smile_cat:

**Comment by rricard** [comment]
Yeah ok, seen it, that's weird ! Doesn't fail for me ...

**Comment by rricard** [comment]
Ok, can you try `git mv roles/git/vars roles/git/defaults` and relaunch ansible ? If it works, I think, we've found a new convention for these roles !

**Comment by octplane** [comment]
Works !

**Comment by rricard** [comment]
Followup in #12
