### ISSUE TITLE
"ensure bash_profile presence" very dangerous

### ISSUE THREAD

**Issue by paulp** [osxc/legacy-common#8]
The way dotfile resolution takes place on OSX, if you create a .bash_profile it is positioned in front of - and instead of - .profile. That means creating .bash_profile effectively disables .profile, which in my case is massively breaky.

More generally, it would be great if there was some more structured way to manipulate environment variables than appending strings to one possible dotfile. A project such as this might be an unusually good opportunity to bring about such a thing.

**Comment by rricard** [comment]
Yes, I agree but many of the existing projects I importing there (rbenv, hub, ...) advise to put the configuration in .bash_profile. As I just ensure that one line is present in this file, you could something like this: rename .profile to .bash_profile or source .bash_profile in .profile. But I'm open to discussion here because appending strings to the only dotfile here can be tricky ...

**Comment by paulp** [comment]
I realize I can play defense against this sort of outcome by creating a .bash_profile, but I'm thinking of the rest of the world. It's really not uncommon to configure one's environment via .profile. The bash documentation says:

"After reading that file, it looks for ~/.bash_profile, ~/.bash_login, and ~/.profile, in that order, and reads and executes commands from the first one that exists and is readable."

That indicates that the only file which can be safely modified (at least safely with respect to not disabling existing files) is the latest one in that list which exists.

**Comment by rricard** [comment]
Ok, in this case, I let you do a pull-request to change this behavior ... I'm not a bash user so I wasn't aware of this problem. Thanks for your feedback :)

**Comment by ninjabong** [comment]
I just submitted a pull-request that should fix this, however there's a deeper chicken-egg problem with cask using ~/Applications instead of /Applications because this line isn't present on a fresh clean system so during the initial ansible-playbook run it doesn't know about HOMEBREW_CASK_OPTS.
